package style

type SeparatorType = string

const (
	SeparatorLazy         SeparatorType = "\u0000"
	SeparatorNone         SeparatorType = ""
	SeparatorSpace        SeparatorType = " "
	SeparatorSlash        SeparatorType = "/"
	SeparatorBackslash    SeparatorType = "\\"
	SeparatorComma        SeparatorType = ","
	SeparatorCaret        SeparatorType = "^"
	SeparatorAmpersand    SeparatorType = "&"
	SeparatorAsterisk     SeparatorType = "*"
	SeparatorPeriod       SeparatorType = "."
	SeparatorColon        SeparatorType = ":"
	SeparatorSemicolon    SeparatorType = ";"
	SeparatorQuestion     SeparatorType = "?"
	SeparatorUnderscore   SeparatorType = "_"
	SeparatorVerticalBar  SeparatorType = "|"
	SeparatorEqual        SeparatorType = "="
	SeparatorPlus         SeparatorType = "+"
	SeparatorMinus        SeparatorType = "-"
	SeparatorHyphen       SeparatorType = "-"
	SeparatorQuote        SeparatorType = "'"
	SeparatorDoubleQuote  SeparatorType = "\""
	SeparatorLess         SeparatorType = "<"
	SeparatorGreater      SeparatorType = ">"
	SeparatorBackQuote    SeparatorType = "`"
	SeparatorTilde        SeparatorType = "~"
	SeparatorExclaim      SeparatorType = "!"
	SeparatorAt           SeparatorType = "@"
	SeparatorNumber       SeparatorType = "#"
	SeparatorDoller       SeparatorType = "$"
	SeparatorPercent      SeparatorType = "%"
	SeparatorParenLeft    SeparatorType = "("
	SeparatorParenRight   SeparatorType = ")"
	SeparatorBracketLeft  SeparatorType = "["
	SeparatorBracketRight SeparatorType = "]"
	SeparatorBraceLeft    SeparatorType = "{"
	SeparatorBraceRight   SeparatorType = "}"
)
